### ISSUE TITLE
Реализовать функцию атаки

### ISSUE THREAD

**Issue by eugene-serb** [eugene-serb/battleships#16]
### Описание

Реализовать функцию атаки

### Гипотеза решения

Реализовать функцию `attack`, которая принимает координаты `x`, `y` и `player`, по которому будет совершена атака. Функция возвращает `boolean`, где `true` — успешная атака, а `false` — неуспешная. Функция вызывает функцию `explodeShip`, которая повреждает соседние клетки от корабля.

**Comment by georgiy-nogovitsyn** [comment]
@eugene-serb это для игрока только?
Функция не должна проверять корректность передаваемых координат?

Также функцию отрисовки "теней" по диагонали думаю лучше назвать иначе `damagedShipShades`
