### ISSUE TITLE
Исправить работу генерацию кораблей

### ISSUE THREAD

**Issue by eugene-serb** [eugene-serb/battleships#24]
### Описание

Исправить работу генерацию кораблей.

### Ожидаемый результат

Корабли генерируются
- на дистанции друг от друга хотя бы в одну клетку
- не вылезают за края карты
- 4 однопалубных, 3 двухпалубных, 2 трёхпалубных, 1 четырёхпалубный.

### Фактический результат

![Image](https://github.com/eugene-serb/battleships/assets/46799701/a0001175-b9f0-49b4-9ca5-18e96192955c)

### Связи

#8
#13

**Comment by mireal** [comment]
![image](https://github.com/eugene-serb/battleships/assets/19926718/094e61e4-de57-4fcd-aed2-c2ce852df360)

**Comment by eugene-serb** [comment]
Рано закрываешь
